### ISSUE TITLE
browser extension

### ISSUE THREAD

**Issue by erayarslan** [evilsocket/veryfied#1]
Just a fun idea, but we can create browser extension with [verified.csv](https://github.com/evilsocket/veryfied/blob/main/verified.csv)
with that, we can replace verified icon with ours :D

**Comment by evilsocket** [comment]
that's exactly what https://github.com/evilsocket/veryfied/tree/main/ext is.

**Comment by erayarslan** [comment]
oh. sorry i missed that part 🥲 thanks.
