### ISSUE TITLE
Firefox support - Manifest v2

### ISSUE THREAD

**Issue by browny99** [evilsocket/veryfied#2]
I just installed the extenstion in Firefox, however it doesn't work out of the box...

Firefox doesn't support Manifest v3 (yet), but you're extenstion is (as far as I can tell) fully compatible with Manifest v2. I installed it manually in my Browser with the 3 changed to 2 and it seems to work.

### Suggestion
Create a release for Chromium with v3 in manifest.json and v2 for Firefox.

**Comment by evilsocket** [comment]
oh gosh ... chrome says v2 is gonna be deprecated in 2023, firefox doesn't load v3 ... love working with browsers! :'D thanks for the report

**Comment by browny99** [comment]
for the things you are doing, you can probably keep the code compatible with both... 
The things outlined [here](https://developer.chrome.com/docs/extensions/mv3/mv3-migration/) are probably not required, since the data doesn't change anymore and code updates can be distributed in the addon package itself.

**Comment by evilsocket** [comment]
Added some instructions with https://github.com/evilsocket/veryfied/commit/9e24a3d7b82f18f01b5c7f62c4763959e5db89d5 ...

**Comment by evilsocket** [comment]
will close this for now, the code is 100% compatible with both browsers and as long as i don't prepackage the extension and i provide instructions all is well :)
